const state={data:null,unit:null,tab:'photos',gallery:[],index:0};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
async function init(){try{const r=await fetch('data.json');if(!r.ok)throw Error(r.status);state.data=await r.json();render();const id=location.hash.slice(1);if(state.data.units.some(u=>u.id===id))selectUnit(id,false)}catch(e){$('#unitGrid').innerHTML='<p class="empty">โหลดข้อมูลไม่สำเร็จ กรุณารีเฟรชหน้า</p>';console.error(e)}}
function render(){const d=state.data;$('#floorplan').src=d.plan;$('#unitCount').textContent=d.units.length+' UNITS';$('#unitGrid').innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-label','แตะยูนิตบนแผนผัง');$('#planHotspots').replaceChildren(svg);
 for(const u of d.units){const card=document.createElement('button');card.className='unit-card';card.dataset.unit=u.id;card.innerHTML=`<div class="unit-cover"><img src="${esc(u.photos[0].src)}" alt="ภาพสี Kitchen ${esc(u.id)}" loading="lazy"></div><div class="unit-card-body"><span class="unit-tag">UNIT ${esc(u.id)}</span><h3>Kitchen ${esc(u.id)}</h3><p>${u.photos.length} ภาพสี · ${u.drawings.length} แบบ</p><span class="card-action">ดูรายละเอียด ↗</span></div>`;card.addEventListener('click',()=>selectUnit(u.id));$('#unitGrid').append(card);
 const poly=document.createElementNS(svg.namespaceURI,'polygon');poly.setAttribute('points',u.hotspot.map(p=>p.join(',')).join(' '));poly.setAttribute('tabindex','0');poly.setAttribute('role','button');poly.setAttribute('aria-label','เปิดยูนิต '+u.id);poly.dataset.unit=u.id;poly.addEventListener('click',()=>selectUnit(u.id));poly.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();selectUnit(u.id)}});svg.append(poly)} }
function selectUnit(id,update=true){state.unit=state.data.units.find(u=>u.id===id);if(!state.unit)return;state.tab='photos';$('#unitDetail').hidden=false;$('#detailId').textContent=id;$('#detailHeading').textContent='Kitchen '+id;$('#detailDate').textContent='วันที่แบบ '+state.unit.date;$('#detailMeta').textContent='FLOOR 3';document.querySelectorAll('[data-unit]').forEach(el=>el.classList.toggle('selected',el.dataset.unit===id));if(update)history.replaceState(null,'','#'+id);renderTab();$('#unitDetail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
function gallery(items){state.gallery=items;return `<div class="gallery-grid">${items.map((x,i)=>`<button class="gallery-item" data-image="${i}"><img src="${esc(x.src)}" alt="${esc(x.title)}" loading="lazy"><span>${esc(x.title)}</span><small>หน้า ${x.page} · แตะเพื่อขยาย</small></button>`).join('')}</div>`}
function link(path,label,download=false){return `<a class="download" href="${esc(path)}" ${download?'download':'target="_blank" rel="noopener"'}>${esc(label)} ${download?'↓':'↗'}</a>`}
function renderTab(){document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===state.tab;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});const u=state.unit,c=$('#tabContent');if(['photos','drawings'].includes(state.tab)){const items=u[state.tab];c.innerHTML=`<p class="content-note">${state.tab==='photos'?'ภาพจำลองสีจากเอกสารออกแบบ ไม่ใช่ภาพถ่ายหน้างาน':'แบบสำหรับอ้างอิงรายละเอียด กรุณาตรวจขนาดจาก PDF ต้นฉบับ'}</p>${link(u.documents[state.tab],state.tab==='photos'?'เปิด PDF ภาพสี':'เปิด PDF แบบ')}${gallery(items)}`}
 else if(state.tab==='price'){const p=u.price;if(p.status!=='approved'){c.innerHTML='<p class="empty">รอยืนยันเอกสารราคาสำหรับลูกค้า</p>';return}c.innerHTML=`<div class="price-box"><div class="eyebrow">${p.type==='change-order'?'CHANGE ORDER · ยอดเพิ่ม–ลดงาน':'CUSTOMER QUOTATION · ราคาสำหรับลูกค้า'}</div><h3>฿ ${money(p.amount)}</h3><p>${esc(p.note)}</p><p>เอกสารวันที่ ${esc(p.date)}</p>${p.type==='change-order'?'<strong class="warning">ยอดนี้ไม่ใช่ราคารวมครัว 3D</strong>':''}</div><p class="content-note">ราคาตามเอกสารที่แนบ ไม่ใช่การยืนยันสถานะชำระเงินหรือยอดคงค้าง</p>${link(p.pdf,'เปิดใบสรุปราคา')}${link(p.pdf,'ดาวน์โหลดใบสรุปราคา',true)}${gallery(p.images)}`}
 else {state.gallery=[];c.innerHTML='<p class="content-note">ชุดเอกสารสำหรับลูกค้า: ภาพสี + แบบ + ใบสรุปราคา ไม่รวมเอกสารต้นทุนภายใน ข้อมูลเก่า และลายเซ็น</p><div class="download-list">'+link(u.documents.all,'ดาวน์โหลดชุดเอกสารรวม '+u.id,true)+link(u.documents.photos,'ดาวน์โหลดภาพสี PDF',true)+link(u.documents.drawings,'ดาวน์โหลดแบบ PDF',true)+link(u.price.pdf,'ดาวน์โหลดใบสรุปราคา PDF',true)+'</div>'}document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>openImage(Number(b.dataset.image))))}
function openImage(i){state.index=i;showImage();if(!$('#galleryModal').open)$('#galleryModal').showModal()}
function showImage(){const x=state.gallery[state.index];$('#modalImage').src=x.src;$('#modalImage').alt=x.title;$('#modalTitle').textContent=state.unit.id+' · '+x.title;$('#modalCaption').innerHTML=`${state.index+1} / ${state.gallery.length} · หน้า ${x.page} · ${link(x.src,'เปิดภาพขนาดเต็ม')}`;$('#prevImage').disabled=state.gallery.length<2;$('#nextImage').disabled=state.gallery.length<2}
function step(n){state.index=(state.index+n+state.gallery.length)%state.gallery.length;showImage()}
document.addEventListener('DOMContentLoaded',()=>{init();document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderTab()});b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(b),next=tabs[(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];next.click();next.focus()}})});$('#backBtn').addEventListener('click',()=>{$('#unitDetail').hidden=true;history.replaceState(null,'',location.pathname);$('.overview').scrollIntoView({behavior:'smooth'})});$('#closeModal').addEventListener('click',()=>$('#galleryModal').close());$('#prevImage').addEventListener('click',()=>step(-1));$('#nextImage').addEventListener('click',()=>step(1));$('#galleryModal').addEventListener('click',e=>{if(e.target.id==='galleryModal')e.target.close()});document.addEventListener('keydown',e=>{if($('#galleryModal').open&&['ArrowLeft','ArrowRight'].includes(e.key))step(e.key==='ArrowRight'?1:-1)})});
