const state={data:null,floor:4,unit:null,section:null,tab:'photos',gallery:[],index:0};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const floorUnits=()=>state.data.units.filter(u=>Number(u.floor)===state.floor);
const findUnit=id=>state.data.units.find(u=>u.id.toUpperCase()===id.toUpperCase());
function parseHash(){const raw=decodeURIComponent(location.hash.slice(1));if(!raw)return null;const lower=raw.toLowerCase();const direct=state.data.units.find(u=>u.id.toLowerCase()===lower);if(direct)return{id:direct.id,section:null};const room=state.data.units.flatMap(u=>u.sections).find(s=>s.id.toLowerCase()===lower);if(room)return{id:state.data.units.find(u=>u.sections.includes(room)).id,section:room.id};return null}
function setFloor(f){state.floor=Number(f);document.querySelectorAll('.floor').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.floor)===state.floor));const plan=state.data.plans[String(state.floor)];$('#floorplan').src=plan.image;$('#floorplan').alt=`แปลนพื้นที่ชั้น ${state.floor}`;$('#planDownload').href=plan.image;$('#planDownload').download=`ARI789-floor-${state.floor}-plan.jpg`;$('#planDownload').textContent=`ดาวน์โหลดแปลนชั้น ${state.floor}`;renderHotspots(plan);renderGrid();}
function renderHotspots(plan){const holder=$('#hotspots');const polys=plan.units.map(u=>{const pts=u.hotspot.map(p=>p.join(',')).join(' ');const c=u.hotspot.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]).map(x=>x/u.hotspot.length);return `<polygon class="hotspot-poly" points="${pts}" data-unit="${esc(u.id)}" tabindex="0" role="button" aria-label="เปิดยูนิต ${esc(u.id)}"><title>เปิด ${esc(u.id)}</title></polygon><a class="hotspot" href="#${esc(u.id)}" style="left:${c[0]}%;top:${c[1]}%" aria-label="เปิดยูนิต ${esc(u.id)}">${esc(u.id)}</a>`}).join('');holder.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="false">${polys}</svg>`;holder.querySelectorAll('.hotspot-poly').forEach(el=>{el.addEventListener('click',()=>selectUnit(el.dataset.unit,true));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectUnit(el.dataset.unit,true)}})});}
function renderGrid(){const grid=$('#unitGrid');const list=floorUnits();if(!list.length){grid.innerHTML='<p class="empty">ยังไม่มีเอกสารตู้เสื้อผ้าสำหรับชั้นนี้</p>';return}grid.innerHTML=list.map(u=>{const pending=u.price.status==='pending';const sectionCount=u.sections.length;return `<a class="unit-card" href="#${esc(u.id)}" data-unit="${esc(u.id)}"><div class="unit-id">${esc(u.id)}</div><div class="unit-label">${esc(u.label)}</div><div class="unit-meta">${sectionCount>1?`${sectionCount} ส่วนห้องแต่งตัว · `:''}${esc(u.date||'')}</div><span class="unit-status">${pending?'รอยืนยันเอกสารราคา':'เอกสารพร้อมตรวจสอบ'}</span></a>`}).join('');grid.querySelectorAll('.unit-card').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();selectUnit(a.dataset.unit,true)}));}
function selectedSections(){if(!state.unit)return[];return state.section?state.unit.sections.filter(s=>s.id===state.section):state.unit.sections;}
function sectionLabel(s){return s.label||s.id}
function galleryItems(kind){return selectedSections().flatMap(s=>(s[kind]||[]).map(x=>({...x,sectionLabel:sectionLabel(s)})));}
function renderSectionNav(){const holder=$('#sectionNav');if(!state.unit||state.unit.sections.length<2){holder.innerHTML='';return}holder.innerHTML=`<button type="button" class="${!state.section?'is-active':''}" data-section="">ทั้งหมด</button>`+state.unit.sections.map(s=>`<button type="button" class="${state.section===s.id?'is-active':''}" data-section="${esc(s.id)}">${esc(s.label)}</button>`).join('');holder.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.section=b.dataset.section||null;renderSectionNav();renderTab()}));}
function renderGallery(kind){const items=galleryItems(kind);if(!items.length)return '<p class="empty">ยังไม่มีเอกสารหมวดนี้</p>';state.gallery=items;return `<div class="gallery-grid">${items.map((x,i)=>`<button class="gallery-card" type="button" data-index="${i}"><img src="${esc(x.src)}" alt="${esc(x.title)}" loading="lazy"><span>${esc(x.title)}${state.unit.sections.length>1?` · ${esc(x.sectionLabel)}`:''}</span></button>`).join('')}</div>`}
function renderPrice(){const sections=selectedSections();return `<div class="price-grid">${sections.map(s=>{const p=s.price;if(p.status==='pending')return `<article class="price-card"><h3>${esc(sectionLabel(s))}</h3><div class="amount">รอยืนยันเอกสารราคา</div><p>${esc(p.note)}</p></article>`;return `<article class="price-card"><h3>${esc(sectionLabel(s))}</h3><div class="amount">฿ ${money(p.amount)}</div><p>${esc(p.note||'ยอดรวมตามใบสรุปราคา รวม VAT 7%')}</p>${p.images?.map(x=>`<button class="gallery-card price-preview" type="button" data-price-src="${esc(x.src)}"><img src="${esc(x.src)}" alt="${esc(x.title)}" loading="lazy"><span>${esc(x.title)}</span></button>`).join('')||''}</article>`}).join('')}</div>`}
function renderDownloads(){const links=[];selectedSections().forEach(s=>{const d=s.documents;const prefix=state.unit.sections.length>1?`${sectionLabel(s)} · `:'';if(d.photos)links.push([`${prefix}ภาพสี`,d.photos,'PDF · เฉพาะหน้าภาพสี']);if(d.drawings)links.push([`${prefix}แบบ`,d.drawings,'PDF · เฉพาะหน้าแบบ']);if(d.price)links.push([`${prefix}ราคา (ปกปิดลายเซ็น)`,d.price,'PDF · สรุปราคา sanitized']);if(d.all)links.push([`${prefix}ชุดเอกสารลูกค้า`,d.all,'PDF · ภาพสี + แบบ + ราคา']);});return `<p class="note">ชุดดาวน์โหลดสาธารณะตัดหน้า QUOTATION / CONFIRM ORDER ออกทั้งหมด และไฟล์สรุปราคาถูก flatten พร้อมปกปิดลายเซ็น/วันที่เขียนมือแล้ว</p><div class="download-list">${links.map(x=>`<a class="download-item" href="${esc(x[1])}" download><span><strong>${esc(x[0])}</strong><small>${esc(x[2])}</small></span><b>ดาวน์โหลด ↓</b></a>`).join('')}</div>`}
function renderTab(){const c=$('#tabContent');if(state.tab==='photos')c.innerHTML=renderGallery('photos');else if(state.tab==='drawings')c.innerHTML=renderGallery('drawings');else if(state.tab==='price')c.innerHTML=renderPrice();else c.innerHTML=renderDownloads();c.querySelectorAll('.gallery-card[data-index]').forEach(b=>b.addEventListener('click',()=>openGallery(Number(b.dataset.index),state.tab==='drawings'?'แบบ':'ภาพสี')));c.querySelectorAll('[data-price-src]').forEach(b=>b.addEventListener('click',()=>{state.gallery=[{src:b.dataset.priceSrc,title:'ใบสรุปราคา'}];openGallery(0,'ราคา')}));}
function selectUnit(id,push=true){const u=findUnit(id);if(!u)return;state.unit=u;state.floor=Number(u.floor);const parsed=parseHash();if(push){const hash=state.section?`#${state.section}`:`#${u.id}`;history.pushState(null,'',hash)}else if(parsed&&parsed.id.toUpperCase()===u.id.toUpperCase())state.section=parsed.section;else state.section=null;setFloor(state.floor);$('#unitDetail').hidden=false;$('#detailEyebrow').textContent=`UNIT ${u.id} · FLOOR ${u.floor}`;$('#detailTitle').textContent=u.label;$('#detailSubtitle').textContent=u.description||'';renderSectionNav();document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('is-active',b.dataset.tab===state.tab);b.setAttribute('aria-selected',b.dataset.tab===state.tab?'true':'false')});renderTab();$('#unitDetail').scrollIntoView({behavior:'smooth',block:'start'});}
function openGallery(index,title){state.index=index;$('#modalTitle').textContent=title;updateModal();const d=$('#galleryModal');if(!d.open)d.showModal()}
function updateModal(){const x=state.gallery[state.index];if(!x)return;$('#modalImage').src=x.src;$('#modalImage').alt=x.title;$('#modalCaption').textContent=`${x.title} · ${state.index+1}/${state.gallery.length}`}
function step(n){state.index=(state.index+n+state.gallery.length)%state.gallery.length;updateModal()}
function renderRoomTable(){const tbody=document.querySelector('#roomTable tbody');if(!tbody||!state.data.rooms)return;tbody.innerHTML=state.data.rooms.map(r=>{const dwg=r.download_dwg;const price=r.has_price?`<a class="dl-btn" href="${esc(r.download_price)}" download>PRICE ↓</a>`:'<span class="badge wait">รอเอกสาร</span>';const money=v=>new Intl.NumberFormat('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);return `<tr><td><span class="room-id">${esc(r.room)}</span></td><td>${r.floor}</td><td><span class="badge ok">มีแบบ</span></td><td>${r.has_price?`<span class="badge ok">฿ ${money(r.price_amount)}</span>`:'<span class="badge wait">รอยืนยัน</span>'}</td><td><a class="dl-btn" href="${esc(dwg)}" download>แบบ ↓</a> ${price} <a class="dl-btn" href="${esc(r.download_set)}" download>แบบ+ราคา ↓</a></td></tr>`}).join('')}
async function init(){try{const r=await fetch('data.json');if(!r.ok)throw Error(r.status);state.data=await r.json();setFloor(4);renderRoomTable();const parsed=parseHash();if(parsed){state.section=parsed.section;selectUnit(parsed.id,false)}}catch(e){console.error(e);$('#unitGrid').innerHTML='<p class="empty">โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่</p>'}}
window.addEventListener('hashchange',()=>{if(!state.data)return;const p=parseHash();if(p){state.section=p.section;selectUnit(p.id,false)}else{$('#unitDetail').hidden=true;state.unit=null;state.section=null}});
window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.floor').forEach(b=>b.addEventListener('click',()=>{state.section=null;state.unit=null;$('#unitDetail').hidden=true;history.replaceState(null,'',location.pathname);setFloor(b.dataset.floor);document.querySelector('.overview').scrollIntoView({behavior:'smooth'})}));document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-selected',x===b?'true':'false')});renderTab()}));document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;const tabs=[...document.querySelectorAll('.tab')];const i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();tabs[(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length].focus()});$('#backBtn').addEventListener('click',()=>{$('#unitDetail').hidden=true;state.unit=null;state.section=null;history.replaceState(null,'',location.pathname);document.querySelector('.overview').scrollIntoView({behavior:'smooth'})});$('#closeModal').addEventListener('click',()=>$('#galleryModal').close());$('#prevImage').addEventListener('click',()=>step(-1));$('#nextImage').addEventListener('click',()=>step(1));$('#galleryModal').addEventListener('click',e=>{if(e.target.id==='galleryModal')e.target.close()});document.addEventListener('keydown',e=>{if($('#galleryModal').open&&['ArrowLeft','ArrowRight'].includes(e.key))step(e.key==='ArrowRight'?1:-1)});init()});
